
tasks:
  - before: code --install-extension redhat.java
  - init: |
      sdk default java 17.0.8.fx-zulu
      mvn install -f ./net.winklerweb.tabnine.parent/pom.xml

vscode:
  extensions:
    - redhat.java
