
tasks:
  - before: code --install-extension redhat.java
  - init: |
      sdk install java 17.0.8-amzn
      mvn install -f ./net.winklerweb.tabnine.parent/pom.xml

vscode:
  extensions:
    - redhat.java
