name: Build and Publish p2 Update Site

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
      - name: Build with Maven
        run: mvn clean package -f ./net.winklerweb.tabnine.releng/pom.xml
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './net.winklerweb.tabnine.updatesite/target/repository'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2