name: Build and Publish p2 Update Site

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn clean verify
      - name: Publish p2 update site
        uses: iloveeclipse/p2-publish-action@v1.0.0
        with:
          site-root: /update-site
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './net.winklerweb.tabnine.updatesite/target/repository'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2